name: Mypy

on: [push, workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh |
            bash -s -- --batch
        conda env create -f env-dev.yml
        conda run --name maize-dev pip install --no-deps .
        conda run --name maize-dev pip install types-PyYAML types-toml
    - name: Analysing the code with mypy
      run: |
        conda run --name maize-dev mypy --strict --explicit-package-bases maize/core maize/utilities maize/steps
