name: Pylint

on: [push, workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      id: conda-cache
      with:
        path: ./miniconda3
        key: ${{ runner.os }}-conda-${{ hashFiles('**/env-dev.yml') }}
        restore-keys: |
          ${{ runner.os }}-conda-${{ hashFiles('**/env-dev.yml') }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      if: steps.conda-cache.outputs.cache-hit != true
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh |
            bash -s -- --batch
        conda env create -f env-dev.yml
        conda run --name maize-dev pip install --no-deps .
    - name: Analysing the code with pylint
      run: |
        conda run --name maize-dev pylint --exit-zero maize/core maize/utilities maize/steps
