# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest-quick

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      role:
        required: true
        type: string
        default: "test"
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh |
            bash -s -- --batch
        conda env create -f env-dev.yml
        conda run --name maize-dev pip install --no-deps .
    - name: Run fast test suite with pytest
      run: |
        conda run --name maize-dev pytest --cov=maize --cov-branch --cov-report xml -k "not random" ./tests
    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: ${{ github.workspace }}/coverage.xml
